### ISSUE TITLE
Miscellaneous: Simple ToDo app with NodeJs

### ISSUE THREAD

**Issue by Pranav-yadav** [IEEESFIT1/OpenOctober#637]
### Simple ToDo app using Express Server with NodeJs
- [x] Creates new server using Express
- [x] Listens for GET & POST requests on defined port
- [x] Creates local ToDo app db
- [x] Responds to GET requests, with all existing ToDo's
- [x] Responds to GET request with ID, with specific todo
- [x] Creates new ToDo using POST requests with json data

**Comment by Pranav-yadav** [comment]
Hi @orvil1026 ,
I've worked on this issue and all 6 tasks, please assign this issue to me; if this app is not there already.

**Comment by Pranav-yadav** [comment]
Hi @orvil1026 👋,
✅ This PR has passed all checks, please review and merge✨.
🚀
