### ISSUE TITLE
 PWA Dev: 'Weather' Progressive Web Application 🏞🌈

### ISSUE THREAD

**Issue by Pranav-yadav** [IEEESFIT1/OpenOctober#784]
# **Weather PWA**
### Tasks:

- [x] `index.js` //driver js
- [x] `App.js` //js logic
- [x] `fetchWeather.js` //fetches weather info for given city using OpenWeatherMap API
- [x] `serviceworker.js` // helps to make this app installable through web browsers
- [x] `manifest.json`    //  ⬆
- [x] `offline.html` // offline page, when user is offline
